---
- hosts: all
  environment: "{{proxy_env}}"

  tasks:

  - name: install desktop
    become: true
    package: name={{item}} state=present
    with_items:
    - language-pack-de
    - ubuntu-desktop

    
  roles:
  - role: gantsign.keyboard
    become: true
    keyboard_model: pc105
    keyboard_layout: de