keycloak:
  auth-server-url: https://{{ hostvars['mlp-vm'].ansible_host  }}/auth/
  resource: backend
  realm: mlp
  public-client: true
  principal-attribute: preferred_username
  bearer-only: true
server:
  servlet:
    context-path: /api