keycloak:
  auth-server-url: https://172.28.128.5/auth/
  resource: backend
  realm: mlp
  public-client: true
  principal-attribute: preferred_username
  bearer-only: true
server:
  servlet:
    context-path: /api