---
- src: geerlingguy.docker
  version: 2.5.1
- src: geerlingguy.java
  version: 1.9.4
- src: gantsign.maven
  version: 5.3.0
- src: gantsign.intellij
  version: 5.3.0
- src: gantsign.keyboard
  version: 1.4.0
